### ISSUE TITLE
Timer issue while run into grbl, it's a difference with a uno block.

### ISSUE THREAD

**Issue by yiivon** [wokwi/avr8js#101]
I run this https://github.com/gnea/grbl/releases/download/v1.1h.20190825/grbl_v1.1h.20190825.hex with avr8js' demo, serial just output "e", it seems that there is something about timer's difference between avr8js and a truth arduino uno.

**Comment by urish** [comment]
Can you try on https://wokwi.com/arduino/new and then press "F1" and choose "Load HEX File and Start Simulation" and see if it works better?

**Comment by urish** [comment]
Closing due to lack of response. Feel free to comment if you have any more questions
