### ISSUE TITLE
Arduino Mega 2560: Analog inputs A8 ... A15

### ISSUE THREAD

**Issue by Koepel** [wokwi/avr8js#105]
The analog inputs A8 ... A15 are just copies of A0 ... A7 on the Arduino Mega board.

Wokwi test simulation: https://wokwi.com/arduino/projects/308791757053624896

When I want to make a Wokwi project for the Arduino forum, then sometimes those analog inputs are used and the project can not be simulated in Wokwi.

**Comment by urish** [comment]
Thank you so much for the detailed bug report! 

This should be fixed now. I reworked the entire ADC peripheral from the [hacky 6-line implementation](https://github.com/wokwi/avr8js/issues/13#issuecomment-680051744) we had into something a bit more complete. This means we should also support setting the reference voltage to internal 1.1V and even [differential channels](https://github.com/wokwi/avr8js/blob/e35214d597cf538e6505ed155aff6b77917aa246/src/peripherals/adc.ts#L142). I haven't had a chance to test these features yet, but they are merged in wokwi.com, so they should be available as well.
