### ISSUE TITLE
Watchdog Timer

### ISSUE THREAD

**Issue by TimMathias** [wokwi/avr8js#106]
Could you implement the watchdog timer please?

**Comment by urish** [comment]
Register description can be found in pages 63-65 / section 11.9 of the [datasheet](https://ww1.microchip.com/downloads/en/DeviceDoc/ATmega48A-PA-88A-PA-168A-PA-328-P-DS-DS40002061A.pdf).

**Comment by urish** [comment]
Done!

Usage example: https://wokwi.com/arduino/projects/309372800631571009
