### ISSUE TITLE
Question in regards of how does portConfig works

### ISSUE THREAD

**Issue by Sharvin26** [wokwi/avr8js#109]
Hello, 

First of all, thank you for developing such a great library.

I completed this [video tutorial](https://youtu.be/fArqj-USmjA) that I found in the readme of this project.

Now when I tried changing the port from `portDConfig` to `portBConfig` or something else, the LED stopped working.

**Working:**
```
const port = new AVRIOPort(cpu, portDConfig);
```

**Not Working:**
```
const port = new AVRIOPort(cpu, portBConfig);
```

I also tried changing the pin both in code and this code snippet below:
 
**Working:**
```
port.addListener(() => {
      const turnOn = port.pinState(7) === PinState.High;
      setLedState(turnOn);
});
```

**Not Working:**
```
port.addListener(() => {
      const turnOn = port.pinState(8) === PinState.High;
      setLedState(turnOn);
});
```

What I observed was it worked for 0 to 7 but stopped working for numbers bigger than 7. 

I made sure the number here and in arduino code are same.

I was going through the issues of this project to understand what I was doing wrong and I found a [discussion](https://github.com/wokwi/avr8js/issues/67#issuecomment-728121667) where the author of this repo has commented.

But I still didn't understood how this is working.

I am more confused when various arduino boards are brought in. 

For example:

Arduino Mega has 0 to 53 Digital GPIO Pins. So now to determine port for each pin number I went to the arduino code 

https://github.com/arduino/ArduinoCore-avr/blob/60f0d0b125e06dbf57b800192c80e5f60d681438/variants/mega/pins_arduino.h#L162

Thanks to above mentioned github discussion I found this.

Now I am wondering why other portConfig are not working except `portDConfig` and why only range 0 to 7 is working.

This is the sandbox link attached [here](https://codesandbox.io/s/nice-forest-8i5h7?file=/src/App.js).

Any help in this matter would be appreciated as I am much of beginner in electronics and trying to understand how everything is combining together for educational purpose.

**Comment by urish** [comment]
Hi Sharvin,

Nice to meet you!

In general, each port has up to 8 pins (most of them have 8). For Arduino Uno, the mapping is as follows:

* pins 0 to 7 are on Port D (0..7)
* pins 8 to 13 are on Port B (0..5)
* pins A0..A5 are on Port C (0..5)

So if you wanted to listen for Arduino's pin 8, that'd correspond to pin number 0 (the first pin) on Port B, and the code would look something like:

```js
const portB = new AVRIOPort(cpu, portBConfig);
portB.addListener(() => {
      const turnOn = port.pinState(0) === PinState.High;
      setLedState(turnOn);
});
```

For Arduino mega, it's a similar concept, and I see that you have already found the mapping. Here's an example how to read these lines:

```
	PG	, // PG 2 ** 39 ** D39	
```

The first part of the comment is the port name (G) and pin index in the port (2), and the second part is the Mega pin number. 

So what this line says: Mega pin 39 is pin 2 on Port G. So you would listen it using something like:

```
const portG = new AVRIOPort(cpu, portGConfig);
portG.addListener(() => {
      const turnOn = port.pinState(2) === PinState.High;
      setLedState(turnOn);
});
```

I hope this is helpful!
