### ISSUE TITLE
Bug? Attiny85 + WatchDog Timer

### ISSUE THREAD

**Issue by makkiato83** [wokwi/avr8js#134]
Hello, 

this is a fantastic project and I am very new to it. 
Thank you for all you did so far!

I think I have spotted a bug with the simulation of the ATTiny85. 

Here is the sketch: https://wokwi.com/projects/352946303296633857

This is supposed to blink the led every ~1sec. 
And it does on a real ATTiny85.

However, during the simulation, the led is always ON.

**Comment by urish** [comment]
Thanks for reporting, fixed!
