### ISSUE TITLE
Editor UX - Save user history to localStorage on emulation run

### ISSUE THREAD

**Issue by LironHazan** [wokwi/avr8js#24]
It will improve development experience if we'll save the cpp code every time the user hits "run simulation".

I suggest adding a tiny util which abstracts (safely) the  localStorage.addItem and localStorage.removeItem.
state machine: 
check if there's a localstorage entry:
yes: remove it and add a new one.
No: add one.

** see TS playground as a reference.

**Comment by urish** [comment]
It's worth adding a "Revert code" button (or similar) that removes the localStorage code and loads again the initial sample code

**Comment by LironHazan** [comment]
@urish will do
