### ISSUE TITLE
usart.ts code typo?

### ISSUE THREAD

**Issue by yiivon** [wokwi/avr8js#51]
src/peripherals/usart.ts line 103
` if (ucsrb & UCSRA_TXC && ucsrb & UCSRB_TXCIE) {`
is `ucsra & UCSRA_TXC` ?

**Comment by urish** [comment]
So it seems! 

How did you come across this issue?

**Comment by yiivon** [comment]
> So it seems!
> 
> How did you come across this issue?

I am trying to implement the Rx part hardly and ..., so, you see

**Comment by urish** [comment]
The Rx part for AVR8js? as in issue #11 ?

**Comment by yiivon** [comment]
> The Rx part for AVR8js? as in issue #11 ?

Yes

**Comment by urish** [comment]
That's great!

Would you be interested in sending a PR to fix this issue as well?

In addition to fixing the actual issue, a test case which would fail before the fix will be very helpful

**Comment by yiivon** [comment]
I am not very familiar with avr usart, fortunately I seem to have simply implemented the Rx part of it. However, I am not very sure whether this implementation will bring about other undesirable problems, hope helping and  thank you.
![image](https://user-images.githubusercontent.com/1287165/87035199-90f37000-c21b-11ea-8790-bd2f1dfaa8a4.png)
![image](https://user-images.githubusercontent.com/1287165/87035284-b08a9880-c21b-11ea-8543-fe6755341645.png)

**Comment by urish** [comment]
Got it, thanks for reporting!

What are you building?
