### ISSUE TITLE
Mega example only renders first frame on 0.12

### ISSUE THREAD

**Issue by elliottkember** [wokwi/avr8js#66]
I'm trying to update to the latest code, but just can't figure out how to make it work quite right :)

I got pretty far in my 0.12 implementation but got stuck at rendering only the first frame. 

Going to keep investigating and see if I can figure out what changed.

https://stackblitz.com/edit/avr8js-mega-ws2812-mdzn4x?file=package.json

**Comment by urish** [comment]
From my testing so far, it seems like it gets broken starting from version 0.11.1 (0.11.0 works fine), can you confirm if you are observing the same?

**Comment by urish** [comment]
I think I spotted it - can you try changing the value of `FLASH` in `execute.ts` to `0x40000` and see if it helps?

**Comment by elliottkember** [comment]
> I think I spotted it - can you try changing the value of FLASH in execute.ts to 0x40000 and see if it helps?

That works! It seems to be running quite slowly. I'll debug that and see whether that's something in my code.

**Comment by urish** [comment]
Lovely!
